### ISSUE TITLE
Problem in running flink example

### ISSUE THREAD

**Issue by djKooks** [lightbend/fdp-sample-applications#8]
Hello,
I'm currently working with [flink example](https://github.com/lightbend/fdp-sample-applications/tree/develop/apps/flink) in project.
But after activate kafka/zookeeper server and start `ingest`:
```
sbt:ingestRun> ingest
[info] Running (fork) com.lightbend.fdp.sample.flink.ingestion.DataIngestion 
[info] Got /Users/jung/workspace/etc/fdp-sample-applications/apps/flink/source/core/data/nycTaxiFares.csv to process
[info] Got /Users/jung/workspace/etc/fdp-sample-applications/apps/flink/source/core/data/nycTaxiRides.csv to process
```
...it does not go further after this line.

I'm running in local system(not using docker, DC/OS...), and my config is:
```
dcos {

  kafka {
    brokers = "localhost:9092"
    brokers = ${?KAFKA_BROKERS}

    group = "group"
    group = ${?KAFKA_GROUP}

    intopic = "taxiin"
    intopic = ${?KAFKA_IN_TOPIC}

    outtopic = "taxiout"
    outtopic = ${?KAFKA_OUT_TOPIC}

    zookeeper = "localhost:2181"
    zookeeper = ${?ZOOKEEPER_URL}

    ## settings for data ingestion
    loader {
      sourcetopic = ${dcos.kafka.intopic}
      sourcetopic = ${?KAFKA_IN_TOPIC}

      directorytowatch = "/path/to/fdp-sample-applications/apps/flink/source/core/data"
      directorytowatch = ${?DIRECTORY_TO_WATCH}

      pollinterval = 1 second
    }
  }
}
```
I fetched taxi data from http://training.data-artisans.com/exercises/taxiData.html , and put files in `./apps/flink/source/core/data`.
Is there something missing?

Thanks.

**Comment by debasishg** [comment]
Hello @djKooks -

The ingestion process reads data from the `.csv` files and loads into Kafka topic named `taxiin` (as specified in your config file). Check if the topic has been loaded. 

Then you need to follow the steps outlined in https://github.com/lightbend/fdp-sample-applications/blob/develop/apps/flink/README.md#running-taxi-ride-application to run the application that reads from the Kafka topic and does the actual processing.

It looks like u ran the ingestion process but did not run the app. Let me know if this works ..

Thanks.

**Comment by djKooks** [comment]
@debasishg thanks for quick reply! But I got another problem...
```
sbt:fdp-flink-taxiride> run --broker-list localhost:9092 --inTopic taxiin --outTopic taxiOut
[info] Running (fork) com.lightbend.fdp.sample.flink.app.TravelTimePrediction --broker-list localhost:9092 --inTopic taxiin --outTopic taxiOut
[error] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/api/common/serialization/DeserializationSchema
[error] 	at com.lightbend.fdp.sample.flink.app.TravelTimePrediction.main(TravelTimePrediction.scala)
[error] Caused by: java.lang.ClassNotFoundException: org.apache.flink.api.common.serialization.DeserializationSchema
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	... 1 more
[error] java.lang.RuntimeException: Nonzero exit code returned from runner: 1
[error] 	at sbt.ForkRun.processExitCode$1(Run.scala:33)
[error] 	at sbt.ForkRun.run(Run.scala:42)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1185)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1180)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / run) Nonzero exit code returned from runner: 1
```
Can you figure out the problem?

**Comment by debasishg** [comment]
Which version of Flink are you using ?

**Comment by djKooks** [comment]
@debasishg I downloaded flink-1.4.2, but afraid it still causes same error.
My env is:
```
MacOS 10.13
Java 8
Flink 1.4.2
Kafka 1.1.0
```
Is there something more I could try?

**Comment by debasishg** [comment]
Let me try it at my end. Will get back to you.

**Comment by debasishg** [comment]
The error comes since the flink jar is not bundled when we run locally.

Please remove the `provided` clause from `Dependencies.scala` in the flink application (https://github.com/lightbend/fdp-sample-applications/blob/develop/apps/flink/source/core/project/Dependencies.scala#L15-L16). Since we are running locally we need to have the flink jars in classpath. The `provided` clause is required when we run in the container (DC/OS etc.).

Once the process runs, you can monitor the output in the Kafka Topic as ..

```
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning
```

Hope this helps.

**Comment by djKooks** [comment]
@djKooks thanks for quick response.
I removed dependencies you commented, and add flink dependency in `build.sbt` file.
```
...
lazy val taxiRideApp = DockerProjectSpecificAssemblyPlugin.sbtdockerAssemblyFlinkBase("fdp-flink-taxiride", assembly)("./app")

  .settings(libraryDependencies ++= Dependencies.app)
  .settings(libraryDependencies ++= Seq("org.apache.flink" %% "flink-scala" % "1.5.0",
    "org.apache.flink" %% "flink-clients" % "1.5.0",
    "org.apache.flink" %% "flink-streaming-scala" % "1.5.0"))
...
```
Now error not causing, but couldn't find any change in kafka consumer:
```
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning
```

This is taxiride.log in `app/log`. Could you find if it is working well or not?
[taxiride.log](https://github.com/lightbend/fdp-sample-applications/files/2432946/taxiride.log)

Thanks.

**Comment by debasishg** [comment]
You don't have to change anything in `build.sbt` .. just comment the `provided` in `Dependencies.scala` ..

```scala
val flinkScala            =      "org.apache.flink"             %%   "flink-scala"                    % flinkVersion  // % "provided"
val flinkStreamingScala   =      "org.apache.flink"             %%   "flink-streaming-scala"          % flinkVersion // % "provided"
```

The version should be `1.4.2` which is already there. I ran the ingester first, which loads data in the topic `taxiin`. Then ran the app with the `run` command. It takes some time and you will see the application state change to `Running` in the sbt prompt. After some time check the topic `taxiout` .. u will see the output.

**Comment by debasishg** [comment]
Which data set are u using ? You should be using this one ..
```bash
wget http://training.data-artisans.com/trainingData/nycTaxiRides.gz
```

I don't get any exception in my log ..

**Comment by debasishg** [comment]
From your first message I saw u were also using TaxiFares dataset. That should not be used as we don;t use it in the application. Sorry this is not explicit in the documentation. I will change it. Please use only `wget http://training.data-artisans.com/trainingData/nycTaxiRides.gz` ..

**Comment by djKooks** [comment]
@deanwampler yes, I'm now using only `nycTaxiRides` file.
The issue caused above is because number of splited string are different. In `TaxiRide.java`:
```
public static TaxiRide fromString(String line) {
...
    String[] tokens = line.split(",");
    if (tokens.length != 9) {
        throw new RuntimeException("Invalid record: " + line);
    }
...
```
...but splited result are 11.
```
1. 1312
2. END
3. 2013-01-01 00:14:00
4. 2013-01-01 00:06:30
5. -73.981567
6. 40.7729
7. -73.963409
8. 40.765781
9. 2
10. 2013001295
11. 2013001292
```
Also, I tried again after removing length checked line...but process is not being ended...

- Is it right to string have 9 split token?
- How can I know that process ends successfully?

Thanks.

**Comment by debasishg** [comment]
Can u please point me to a line in the file which has > 9 tokens ? May be the line number will help. I think it's ok if we get exceptions for lines having 11 tokens. They will be ignored. 

Regarding the process end, it's not going to end, as it's a streaming process. The output will continue to flow as long as we have input. You can keep on putting files in the same format in the folder and the process will pick them up continuously. Also u can give additional printouts to see actually what's happening.

**Comment by djKooks** [comment]
The file `nycTaxiRides.csv` has a first line as:
```
6,START,2013-01-01 00:00:00,1970-01-01 00:00:00,-73.866135,40.771091,-73.961334,40.764912,6,2013000006,2013000006
...
```
And this has 11 token. I received file by same path as you commented, so I'm wondering what's the problem. Also, I couldn't getting any data from consumer for `taxiout`, so it seem It cannot handle well with the data with 11 token. 
Please let me know If you could find something. Thanks.

**Comment by debasishg** [comment]
hmm .. looks like we are looking at different files ? I have this line in the file and it has 9 tokens ..

```
6,START,2013-01-07 15:27:48,1970-01-01 00:00:00,-73.966742999999994,40.764251999999999,-73.983322000000001,40.743761999999997,1
```

**Comment by djKooks** [comment]
@debasishg yes, I'm not sure why my data includes those data. But regardless of that, it needs to be work well when I remove token check logic:
```
    ~if (tokens.length != 9) {~
~        throw new RuntimeException("Invalid record: " + line);~
~    }~
```

**Comment by djKooks** [comment]
@debasishg still not found the reason...this is my taxiride log.
[taxiride.log](https://github.com/lightbend/fdp-sample-applications/files/2440894/taxiride.log)

Could you find something?

**Comment by debasishg** [comment]
Your log looks ok and I see Kafka commits as well. What does the following give as output ? Do you see any stuff being written into Kafka topic `taxiout` ?

```
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning
```

**Comment by djKooks** [comment]
@debasishg yes...this is what I've done:
1. Run Kafka/Flink server
2. Run `ingest`
3. See log `Got /path/to/fdp-sample-applications/apps/flink/source/core/data/nycTaxiRides.csv to process`
3. Run `sbt:fdp-flink-taxiride> run --broker-list localhost:9092 --inTopic taxiin --outTopic taxiOut`
4. log appears
```
...
info] 10/04/2018 10:26:19      Source: Custom Source -> Filter -> Map(1/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Source: Custom Source -> Filter -> Map(2/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Source: Custom Source -> Filter -> Map(4/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Source: Custom Source -> Filter -> Map(3/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Flat Map -> Sink: Unnamed(1/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Flat Map -> Sink: Unnamed(2/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Flat Map -> Sink: Unnamed(3/4) switched to RUNNING 
[info] 10/04/2018 10:26:19      Flat Map -> Sink: Unnamed(4/4) switched to RUNNING 
```
5. Run `bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning`

After here, consumer log shows:
```
...
2018-10-04T10:26:31,851 INFO [main] org.apache.kafka.common.utils.AppInfoParser - Kafka version : 1.1.0
2018-10-04T10:26:31,851 INFO [main] org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : fdcf75ea326b8e07
2018-10-04T10:26:32,097 INFO [main] org.apache.kafka.clients.Metadata - Cluster ID: h0x4kNfrQwGAnN5RjiYRlA
2018-10-04T10:26:32,100 INFO [main] org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=console-consumer-38643] Discovered group coordinator localhost:9092 (id: 2147483647 rack: null)
2018-10-04T10:26:32,103 INFO [main] org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=console-consumer-38643] Revoking previously assigned partitions []
2018-10-04T10:26:32,103 INFO [main] org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=console-consumer-38643] (Re-)joining group
2018-10-04T10:26:32,120 INFO [main] org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=console-consumer-38643] Successfully joined group with generation 1
2018-10-04T10:26:32,122 INFO [main] org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=console-consumer-38643] Setting newly assigned partitions [taxiout-0]
2018-10-04T10:26:32,139 INFO [main] org.apache.kafka.clients.consumer.internals.Fetcher - [Consumer clientId=consumer-1, groupId=console-consumer-38643] Resetting offset for partition taxiout-0 to offset 0.
```
...and nothing happens anymore.
Is there something wrong?

**Comment by debasishg** [comment]
I think there are a couple of issues here .. These are the steps I follow ..

1. Run Kafka (**You don't have to run Flink server. It will run from the embedded docker image**)
2. Run ingestion
```
sbt:root> ingest
[info] Running (fork) com.lightbend.fdp.sample.flink.ingestion.DataIngestion 
[info] Got /Users/debasishghosh/tt/nycTaxiRides.csv to process
```
3. In another sbt terminal, run the app
```
sbt:root> project fdp-flink-taxiride
[info] Set current project to fdp-flink-taxiride (in build file:/Users/debasishghosh/lightbend/fdp/fdp-sample-applications/apps/flink/source/core/)
sbt:fdp-flink-taxiride> run --broker-list localhost:9092 --inTopic taxiin --outTopic taxiout
[info] Running (fork) com.lightbend.fdp.sample.flink.app.TravelTimePrediction --broker-list localhost:9092 --inTopic taxiin --outTopic taxiout
[info] kafka set
[info] consumer org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumer011@6a396c1e
[info] rides org.apache.flink.streaming.api.scala.DataStream@7f0eb4b4
[info] Connected to JobManager at Actor[akka://flink/user/jobmanager_1#-34516486] with leader session id 88b27073-edc9-4e19-8659-b6102b66dae3.
[info] 10/04/2018 09:47:59	Job execution switched to status RUNNING.
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(1/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(2/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(3/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(4/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(5/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(6/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(7/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(8/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(1/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(2/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(3/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(4/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(5/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(6/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(7/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(8/8) switched to SCHEDULED 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(1/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(2/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(3/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(4/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(5/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(6/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(7/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(8/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(1/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(2/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(3/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(4/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(5/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(6/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(7/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(8/8) switched to DEPLOYING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(2/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(1/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(4/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(7/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(3/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(6/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(8/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Source: Custom Source -> Filter -> Map(5/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(1/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(2/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(3/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(4/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(5/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(6/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(7/8) switched to RUNNING 
[info] 10/04/2018 09:47:59	Flat Map -> Sink: Unnamed(8/8) switched to RUNNING 
```
4. Monitor the output topic
```
$ pwd
/Users/debasishghosh/software/kafka/kafka_2.12-1.0.0
Debasishs-MacBook-Pro:kafka_2.12-1.0.0 debasishghosh$ bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning
1984203,2
2031201,0
1999986,17
1978093,12
1988590,14
1985447,4
1961099,4
1979586,2
1980663,5
1971676,7
2001064,30
1978566,7
...
```

Let me know if this helps ..

**Comment by djKooks** [comment]
@debasishg sorry, not working. I'm not sure what's the reason...

**Comment by debasishg** [comment]
@djKooks I think I spotted where things are problem for you ..

In Step 4, you are doing the following:

Step 4: Run `sbt:fdp-flink-taxiride> run --broker-list localhost:9092 --inTopic taxiin --outTopic taxiOut`

And here is your Step 5:

Step 5: Run `bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic taxiout --from-beginning`

Note the spelling of the output topic names in the 2 steps. In 4 it is `taxiOut` (`O` in upper case), but in 5 it is `taxiout` (all lower case). It may have started from the fact that there is a typo in the `README` with an uppercase `O` in step 4. Please try all lower case and check.

**Comment by djKooks** [comment]
@debasishg oh, thanks! Now it is working...
Thanks for your help.

It would be better to fix in README...

**Comment by djKooks** [comment]
@debasishg seems README is already been updated. I'll close this one. Thanks!
